---
- name: Setup Axel masternode
  hosts: current
  gather_facts: no
  environment:
    SCW_API_KEY: "{{SCW_API_KEY}}"

  vars:
    servername:"{{ servername}}"
    pub_IP:"{{pub_IP}}"
    masternode_priv_key:"{{ masternode_priv_key }}"
  
  tasks:

  - debug:
      msg: Begin Axel Launch
      
  - name: get Tx Id
    shell: axel-cli masternode outputs
    register: txid

  - name: Add masternode conf
    lineinfile:
      path: /root/.axel/masternode.conf
      line: MN{{ servername}} {{pub_IP}}:32323 {{ masternode_priv_key }} {{ tx_id.stdout }}
      insertafter: EOF

  - name: Desactivate masternode conf
    lineinfile:
      path: /root/.axel/axel.conf
      regexp: '^masternode='
      line: masternode= 1

  - name: stop wallet
    shell: axel-cli stop
  - name: start wallet
    shell: axeld -daemon -conf=/root/.axel/axel.conf -datadir=/root/.axel -debug -logips=1 -forcestart -rescan

  - name : store important variable
  - local_action :
    module: copy
    content: '"txid":{{ txid.stdout }}'
    dest: ./output_data

  - name: status of masternode
    shell: axel-cli masternode status
