---
- name: Setup Scap masternode
  hosts: current
  gather_facts: no
  environment:
    SCW_API_KEY: "{{SCW_API_KEY}}"

  vars:
    serverName: "{{serverName}}"
  
  tasks:

  - name: update and upgrade apt packages
    apt:
      update_cache=yes
      state=latest
      upgrade=yes
     
  - name: launch MN setup
    shell: wget -qO- https://github.com/SafeCapital/mn-installer/releases/latest/download/scap_mn_installer.sh | bash
    
  - name: sleep for 20 seconds
    wait_for: timeout=20
    delegate_to: localhost

  - name: Desactivate masternode conf
    lineinfile:
      path: /root/.safecapital/safecapital.conf
      regexp: '^masternode='
      line: masternode= 0
    
  - name: start wallet
    shell: systemctl start safecapitald.service

  - name: sleep for 20 seconds
    wait_for: timeout=20
    delegate_to: localhost

  - name: generate masternode priv key
    shell: safecapital-cli masternode genkey
    register: masternodeprivkey

  - name: Update masternode priv key
    lineinfile:
      path: /root/.safecapital/safecapital.conf
      regexp: '^masternodeprivkey='
      line: masternodeprivkey= {{ masternodeprivkey.stdout }}

  - name: generate wallet pub key
    shell: safecapital-cli getaccountaddress "MN{{ serverName }}"
    register: pub_key

  - name: sleep for 5 seconds
    wait_for: timeout=5
    delegate_to: localhost

  - name: backup wallet
    shell: safecapital-cli dumpwallet "/root/backup_{{ serverName }}"

  - name: storing backup
    fetch:
      src: backup_{{ serverName }}
      dest: backup/.backup_{{ serverName }}
      flat: yes

  - name: cron empty log file
    lineinfile:
      path: /etc/cron.d/sysstat
      line: "*/10 * * * * root find /root/.safecapital/ -name debug.log -size +1G -exec truncate -s 0 {} \\;"
      insertafter: EOF

  - name: restart crontab
    shell: /etc/init.d/cron force-reload
    
  - name: store important variable
    local_action :
      module: copy
      content: '{"pubKey": "{{ pub_key.stdout }}" , "masternodeprivkey":"{{ masternodeprivkey.stdout }}"}'
      dest: ./.output_data_{{ serverName }}.json

  - name: status of masternode
    shell: safecapital-cli getinfo
    register: status

  - debug:
      var: status