---
- name: Setup Stream masternode
  hosts: current
  gather_facts: no
  environment:
    SCW_API_KEY: "SCW7JVYVXWJ43ZCZNQ0W"

  vars:
    my_priv_key: "{{ my_priv_key }}"
  
  tasks:

  - name: update and upgrade apt packages
    apt:
      update_cache=yes
      state=latest
      upgrade=yes

  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes

  - name: git clone stream MNT install
    git:
      repo='https://github.com/StreamitCoin/stream-install.git'
      dest='./stream'
      version=master
      force=yes
    
  - name: chmod autorize execution
    shell: chmod u+x ./stream/stream-install.sh
     
  - name: launch MN setup
    shell: echo {{ my_priv_key }} | ./stream/stream-install.sh
    
# /user/local/bin/streamitcoind status /////to know the status of the MNT
  # - debug:
      # var: my_ipaddr
  # - debug:
      # var: remote_user