---
- name: Test compute instance lifecycle on a Scaleway account
  hosts: current
  gather_facts: no
  environment:
    SCW_API_KEY: "SCW7JVYVXWJ43ZCZNQ0W"

  vars:
    my_priv_key: "{{ priv_key }}"
  
  tasks:

  - name: update and upgrade apt packages
    apt:
      update_cache=yes
      state=latest
      upgrade=yes

  - name: got to root folder
    shell: cd /root
    
  - name: delete axel install if exists
    shell: rm -f ./axel-install.sh
    
  - name: download axel Mn script
    shell: wget https://raw.githubusercontent.com/axelnetwork/MN-Script/master/axel-install.sh && chmod u+x ./axel-install.sh
    
  - name: launch MN setup
    shell: (echo {{ my_priv_key }}) /root/axel-install.sh -y

  - name: sleep for 40 seconds
    wait_for: timeout=40
    delegate_to: localhost
    

  - name: Finalize install
    shell: mv /root/.axel/debug.log /root/.axel/debug.log-$(date +%y%m%d%H%M) && /root/axel-install.sh --upgrade && axel-cli -version

  # - debug:
      # var: my_ipaddr
  # - debug:
      # var: remote_user