---
- name: Setup Stream masternode
  hosts: current
  gather_facts: no
  environment:
    SCW_API_KEY: "SCW7JVYVXWJ43ZCZNQ0W"

  vars:
    my_priv_key: "{{ my_priv_key }}"
  
  tasks:

  - name: update and upgrade apt packages
    apt:
      update_cache=yes
      state=latest
      upgrade=yes
     
  - name: launch MN setup
    shell: wget -qO- https://github.com/SafeCapital/mn-installer/releases/latest/download/scap_mn_installer.sh | bash
 
  - name: Update masternodeprivkey
    lineinfile:
      path: /root/.safecapital/safecapital.conf
      regexp: '^masternodeprivkey='
      line: masternodeprivkey={{ my_priv_key }}
 
  - name: restart masternode
    shell: systemctl restart safecapitald.service
    
  - name: status of masternode
    shell: 
# /user/local/bin/streamitcoind status /////to know the status of the MNT
  # - debug:
      # var: my_ipaddr
  # - debug:
      # var: remote_user